FROM golang:1.15 as builder
ARG GOPROXY=direct
WORKDIR /go/src/xuzhi.cc/nps
COPY . .
RUN go get -d -v ./... 
RUN CGO_ENABLED=0 go build -ldflags="-w -s -extldflags -static" ./cmd/npc/npc.go

FROM scratch
COPY --from=builder /go/src/xuzhi.cc/nps/npc /
VOLUME /conf
ENTRYPOINT ["/npc"]
